baseURL = "https://www.vietnamtudo.net/"
languageCode = "vi-vn"
title = "Việt Nam Tự Do Đảng"
theme = "minimal"
disqusShortname = "vntd" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "vntd"
    description = "vì một Việt Nam tự do"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Playfair Display" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Trang Chủ"
    weight = 1

[[menu.main]]
    url = "/ve-chung-toi/"
    name = "Về Đảng"
    weight = 2

[[menu.main]]
    url = "/nhung-gia-tri-cot-loi/"
    name = "Những Giá Trị Cốt Lõi"
    weight = 3

[[menu.main]]
    url = "/ung-ho/"
    name = "Ủng hộ"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:vietnamtudodang@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/#"
    name = "twitter"
    weight = 3
